<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="food" targetNamespace="hu.pte.mik.prog4.zh2.ws.soap" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="hu.pte.mik.prog4.zh2.ws.soap" xmlns:ns1="http://ws.zh2.prog4.mik.pte.hu/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://ws.zh2.prog4.mik.pte.hu/" location="FoodDataService.wsdl">
    </wsdl:import>
  <wsdl:binding name="foodSoapBinding" type="ns1:FoodDataService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getFoodData">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getFoodData">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getFoodDataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="food">
    <wsdl:port name="SoapFoodDataServicePort" binding="tns:foodSoapBinding">
      <soap:address location="http://localhost:8081/zh2_ws_feladat_war_exploded/ws/food"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
